-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQguUQBFDAg0BMRZGaC
jEUbxGOINmpx1tkFiZ72ZQtQfxugCgYIKoZIzj0DAQehRANCAAS7Hw5Fq+zsSZpI
jVoovMYAWZAiF64hpu65dYdn/DEEWj+DYYZUHf3K+7skjAJ2PJfxoyBLK6meqMuR
/UGxNsOa
-----END PRIVATE KEY-----